name: SkyConnect Multi-PAN
device: EFR32MG21A020F512IM32
base_project: rcp-uart-802154

gbl:
  fw_type: rcp-uart-802154
  dynamic: ["ezsp_version", "ot_rcp_version", "cpc_version"]
  baudrate: 460800

configuration:
  SL_RAIL_UTIL_PTI_MODE: RAIL_PTI_MODE_DISABLED
  SL_CPC_DRV_UART_VCOM_BAUDRATE: 460800

c_defines:
  CPC_SECONDARY_APP_VERSION_SUFFIX: '"-{git_repo_hash}"'

  SL_CPC_DRV_UART_VCOM_PERIPHERAL: USART0
  SL_CPC_DRV_UART_VCOM_PERIPHERAL_NO: 0

  SL_CPC_DRV_UART_VCOM_TX_PORT: gpioPortA
  SL_CPC_DRV_UART_VCOM_TX_PIN:  6

  SL_CPC_DRV_UART_VCOM_RX_PORT: gpioPortA
  SL_CPC_DRV_UART_VCOM_RX_PIN:  5

  SL_CPC_DRV_UART_VCOM_CTS_PORT: gpioPortB
  SL_CPC_DRV_UART_VCOM_CTS_PIN:  1

  SL_CPC_DRV_UART_VCOM_RTS_PORT: gpioPortB
  SL_CPC_DRV_UART_VCOM_RTS_PIN:  0

  SL_APPLICATION_PRODUCT_ID: '{0xe9, 0x92, 0x67, 0x94, 0xbb, 0x2c, 0x4e, 0xc8, 0x9f, 0x36, 0xd9, 0xc6, 0x79, 0x4a, 0x81, 0xfb}'
