name: SkyConnect OpenThread RCP
device: EFR32MG21A020F512IM32
base_project: ot-rcp

gbl:
  fw_type: ot-rcp
  dynamic: ["ot_rcp_version"]
  baudrate: 460800

configuration:
  SL_RAIL_UTIL_PTI_MODE: RAIL_PTI_MODE_DISABLED
  SL_UARTDRV_USART_VCOM_BAUDRATE: 460800

c_defines:
  SL_UARTDRV_USART_VCOM_PERIPHERAL: USART0
  SL_UARTDRV_USART_VCOM_PERIPHERAL_NO: 0

  SL_UARTDRV_USART_VCOM_TX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_TX_PIN:  6

  SL_UARTDRV_USART_VCOM_RX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RX_PIN:  5

  SL_UARTDRV_USART_VCOM_CTS_PORT: gpioPortB
  SL_UARTDRV_USART_VCOM_CTS_PIN:  1

  SL_UARTDRV_USART_VCOM_RTS_PORT: gpioPortB
  SL_UARTDRV_USART_VCOM_RTS_PIN:  0

  SL_APPLICATION_PRODUCT_ID: '{0xe9, 0x92, 0x67, 0x94, 0xbb, 0x2c, 0x4e, 0xc8, 0x9f, 0x36, 0xd9, 0xc6, 0x79, 0x4a, 0x81, 0xfb}'
