name: Silicon Labs firmware build

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/build.yaml
      - .github/workflows/silabs-firmware-build.yaml
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  sdk_version: 4.2.2

jobs:
  build-container:
    name: Create build container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v2.1.0
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build and Push
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/ksjh/silabs-firmware-builder:${{ env.sdk_version }}
          cache-from: ghcr.io/ksjh/silabs-firmware-builder:cache-${{ env.sdk_version }}
          cache-to: ghcr.io/ksjh/silabs-firmware-builder:cache-${{ env.sdk_version }}
          push: true
          build-args:
            "GECKO_SDK_VERSION=v${{ env.sdk_version }}"

  rcp-multi-pan-firmware-build:
    name: RCP Multi-PAN
    needs: build-container
    strategy:
      matrix:
        include:
          - target: yellow
            device: MGM210PA32JIA
            components: simple_led:board_activity,cpc_security_secondary_none
            patchpath: "RCPMultiPAN/Yellow"
          - target: skyconnect
            device: EFR32MG21A020F512IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/SkyConnect"
          - target: zbdonglee
            device: EFR32MG21A020F768IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/ZBDongleE"
          - target: zbdonglee-230
            device: EFR32MG21A020F768IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/ZBDongleE-230"
          - target: zb-gw04-1v1
            device: EFR32MG21A020F768IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/ZB-GW04-1v1"
          - target: zb-gw04-1v2
            device: EFR32MG21A020F768IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/ZB-GW04-1v2"
          - target: zb-gw04-1v2-230
            device: EFR32MG21A020F768IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/ZB-GW04-1v2-230"
    uses: ./.github/workflows/silabs-firmware-build.yaml
    with:
      firmware_name: rcp-uart-802154-${{ matrix.target }}
      project_file: "/gecko_sdk/protocol/openthread/sample-apps/ot-ncp/rcp-uart-802154.slcp"
      project_name: "rcp-uart-802154"
      device: ${{ matrix.device }}
      components: ${{ matrix.components }}
      patchpath: ${{ matrix.patchpath }}
      sdk_version: 4.2.2
      metadata_fw_type: "rcp-uart-802154"
